version: "3.8"
services:
  openmrs:
    image: openmrs/openmrs-reference-application:2.13.0
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:8080"
  db:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: openmrs_prod
