version: "3.8"
services:
  openmrs:
    image: openmrs/openmrs-reference-application:2.13.0
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - openmrs_test_data:/usr/local/tomcat/.OpenMRS
  db:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: openmrs_test
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  openmrs_test_data:
  mysql_test_data:
